# Define the language environment
language: node_js
# for Docker
sudo: required
services:
  - docker
# Specify the version that shall be used
node_js:
  - "7"
branches:
  only:
    - master

notifications:
  email:
    - henguemelkispro@yahoo.com

install: npm install

before_install:
  - docker build -t urlshortener .
  - docker run -d -p 3000:3000 urlshortener
  - docker ps

# Set environment variables
env:
  - AUTH=true USER=test PASSWORD=test
  - AUTH=false

script:
  - npm run lint
  - npm test
