# Define the language environment
language: node_js
# Specify the version that shall be used 
node_js:
  - "6.1.0"
  - "7"

before_script: npm start

# Set environment variables
env: AUTH=true USER=test PASSWORD=test
