# Define the language environment
language: node_js
# Specify the version that shall be used
node_js:
  - "7"

branches:
  only:
    - master

install: npm install

before_script: npm start

script:
  - npm run lint
  - npm test

# Set environment variables
#env: AUTH=true USER=test PASSWORD=test
